default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: video-access-api_development

test:
  <<: *default
  database: video-access-api_test

production:
  <<: *default
  database: video-access-api_production
  username: video-access-api
  password: <%= ENV['VIDEO-ACCESS-API_DATABASE_PASSWORD'] %>
